const fs=require('fs'); const {JSDOM}=require('jsdom');
const app=fs.readFileSync(require('path').resolve(__dirname,'..','app.js'),'utf8');
const blk=app.slice(app.indexOf('// <<UI-DISPATCHER-BEGIN'),app.indexOf('// UI-DISPATCHER-END>>'));
const names=blk.match(/Object\.freeze\(\{([\s\S]*?)\}\)/)[1].split(',').map(s=>s.trim()).filter(Boolean).filter(n=>n!=='createIndexNoteFromGuide');
const dom=new JSDOM('<div id=outer data-on-click="undoDelete"><button id=b data-on-click="skip" data-args-click="[1]">x</button></div>',{runScripts:'outside-only'});
const w=dom.window; const log=[]; w.__log=log; const errs=[]; w.console.error=(...a)=>errs.push(a.join(' '));
const stubs=names.map(n=> n==='skip' ? "function skip(){ throw new Error('boom'); }" : n==='undoDelete' ? "function undoDelete(){ __log.push('outer ran'); }" : n==='cycleSpeed' ? "function cycleSpeed(){ return Promise.reject(new Error('async boom')); }" : `function ${n}(){}`).join('\n');
w.eval(`var __log=window.__log;${stubs}\nvar NOTE_TEMPLATES={index:{content:()=>''}};\n`+blk.replace(/^\/\/.*$/mg,''));
w.document.getElementById('b').dispatchEvent(new w.MouseEvent('click',{bubbles:true}));
console.log('sync throw contained, ancestor still ran:', log.join()==='outer ran', '| logged:', errs.length===1 && /skip failed/.test(errs[0]));
const a=w.document.createElement('button'); a.setAttribute('data-on-click','cycleSpeed'); w.document.body.appendChild(a);
a.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));
setTimeout(()=>{ console.log('async rejection logged, no crash:', errs.length===2 && /cycleSpeed failed/.test(errs[1])); },20);
